### ISSUE TITLE
Issue with PassiveElementsResistanceParser for Lucius

### ISSUE THREAD

**Issue by Sylvie** [Wisdomb33r/ffch-admin#124]
One of Lucius latent skills is incorrectly parsed:
950132 Destiné carmin

**Comment by Wisdomb33r** [comment]
The counter attack activated skill is categorized in DM as "passive", and therefore interpreted as "passive effect 3" (= elements resistance) rather than "active effect 3" (= stats increase for x turns).

IG the effect is correctly granting ATK. Might be a good idea to ask aEnigma how he can correctly parse the activated skill, even if it is categorized as passive...

**Comment by Wisdomb33r** [comment]
950133 is now categorized as active skill and interpreted correctly by our parser. Gumi apparently changed the configuration for this in a later patch.
