### ISSUE TITLE
Verify handling of skills in Enhancements

### ISSUE THREAD

**Issue by Sylvie** [Wisdomb33r/ffch-admin#258]
The Enhancements were introduced for skills with level base/+1/+2.

The Neo Visions introduce skills with enhancements +3 and +4.

Check that:
- [x] The list of skills is correct for each enhancement level.
- [x] The enhancements are pushed in the DB with the correct skills, base skill and level
- [x] The enhancements are displayed correctly for level +3 and +4 on the website.

**Comment by Wisdomb33r** [comment]
Skills are correctly pushed and displayed on the website (both on the character profile and on the skill page). All the enhancements are displayed. However, there are currently two bugs to solve :

- [ ] In the chaining families pages, the displayed skill is the base one and the +2 one. I suggest this change : only display the max lvl skill (+2 for enhancements, +2 for latents, +5 for brave abilities). This means removing the display of the base skill compared to now.
- [ ] The materials are not displayed correctly due to arithmetic on items identifiers (sigh...). A second algorithm for the forticites must be implemented to shift/unshift 6 identifiers rather than 8.
